# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iTPQtHRfu4CkzyXzHviZPYkidKuZ2XxU
"""

pip install pytearcat

import pytearcat as pt
# Define the coordinates to be used
t,r,theta,phi = pt.coords('t,r,theta,phi')
# Define any constant (more than one constant can be defined at the same time)
Phi = pt.fun('Phi','r')
b = pt.fun('b','r')
g = pt.metric(
    "ds2 = +exp(2*Phi)*dt**2 - dr**2/(1 - b/r) - r**2*(dtheta**2 - sin(theta)**2*dphi**2)"
)



Chr = pt.christoffel()

Chr.display()

# To calculate the default combination of the Ricci Tensor, i.e., (_,_):
Ric = pt.ricci()

# To calculate all the combinations:
# Ric = pt.ricci(All = True)

# To calculate the Ricci Scalar:
RicS = pt.riccis()

# To display the Ricci Tensor (by default it displays the tensor with all lower indices):
Ric.display()

# To display the Ricci Scalar:
pt.display(RicS)

# To calculate the default combination of the Einstein Tensor, i.e., (_,_):
G = pt.einstein()

# To calculate all the combinations:
# G = pt.einstein(All = True)

# To display the Einstein Tensor:
G.display()

# To show the tensor components as a list:
# G.display(aslist = True)

